---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: docker.io/pycontribs/ubuntu:latest
    privileged: True
provisioner:
  name: ansible
verifier:
  name: ansible
